### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Henry-Denny**
Update outdated dependencies for each .toml file in the repository.

### CODE REVIEW

**Comment by DanNixon** [comment]
Looks like you did not start this work on a new branch. It might be easier to just manually apply the changes after switching back to (and pulling changes from) `main`.

**Comment by Henry-Denny** [comment]
Sorry, I thought I had. I used `git checkout -b update-dependencies`. Should I apply the changes on `main` instead?

**Comment by Henry-Denny** [comment]
Ah, I think it might have been because I created the new branch whilst I still had `kafka-daq-report` checked out.

**Comment by DanNixon** [comment]
> Ah, I think it might have been because I created the new branch whilst I still had `kafka-daq-report` checked out.

Ah, yes. That would do it.

**Pull request closed without merging**
