### PR TITLE
Removed TIMESTAMP_FORMAT

### PR DESCRIPTION
**Pull request by Modularius**
## Summary of changes

~~Moved the constant TIMESTAMP_FORMAT to common crate from the Nexus-Writer crate. This constant is used to parse `DateTime` objects into strings. Hence it is more logical to have a common format in a logical place.~~

Removed the constant `TIMESTAMP_FORMAT` from nexus-writer, and replaced its usage with `to_rfc3339()`.

## Instruction for review/testing

Ensure changes to code are as described above.

### CODE REVIEW

**Comment by DanNixon** [comment]
Is this actually needed outside of `nexus-writer`? If not then it would be better left where it is.

Can we just rename it to something that better describes what it is for (i.e. *which* timestamps is this the format for).

**Comment by Modularius** [comment]
It will be used in other crates in one of the other PRs, (I think in the aggregator).

**Comment by DanNixon** [comment]
In what context will it be used there? Even if the formats are the same we should be explicit about what a specific format is for.

As a side note, the format it describes is just RFC 3339, why do we need the format to be explicitly defined outside of the support already provided by `chrono`?

**Comment by Modularius** [comment]
In nexus-writer is is used to specify the format of timestamps that appear as strings in the file format. At the time, it seemed wise to allow us to be flexible with this, but looking back ISO8601 is the standard.
In other crates, I only use it in OpenTelemetry and tracing, so to_rfc3339() will be more than adequate.

I'll change this PR to remove TIMESTAMP_FORMAT and use to_rfc3339() instead.

**Review by DanNixon — APPROVED** [review]

**Pull request merged**
