### PR TITLE
Remove handling of events from `stream-to-file`.

### LINKED ISSUE #113: Trace saving solution
The existing [`stream-to-file`](https://github.com/STFC-ICD-Research-and-Design/supermusr-data-pipeline/tree/main/stream-to-file/src) tool should be adapted to handle saving traces for development/diagnostics.

- Remove handling of events, this is handled by the dedicated NeXus writer
- Allow the ability to consume a control topic, this will handle receiving run start and run stop messages
- If no control topic is provided then the tool behaves as it does now, i.e. continuously save data until it is terminated
- If a control topic is provided then the tool outputs a new HDF file for each run (i.e. from when a run start message is received, up until a run stop message is received)

### PR DESCRIPTION
**Pull request by Henry-Denny**
**Overview of Changes:**

- `stream-to-file` has been renamed to `trace-archiver-hdf5`.
- The handling of events functionality has been removed from this tool.

This partially resolves #113.

### CODE REVIEW

**Comment by DanNixon** [comment]
There is some issue with the Git history of this PR. Did you create the branch fresh from `main` before starting work?

**Comment by Henry-Denny** [comment]
> There is some issue with the Git history of this PR. Did you create the branch fresh from `main` before starting work?

I deliberately created the branch off of the `metrics-for-observability` branch since I had made some changes which I needed to keep.

**Comment by Henry-Denny** [comment]
> > > There is some issue with the Git history of this PR. Did you create the branch fresh from `main` before starting work?
> > 
> > 
> > I deliberately created the branch off of the `metrics-for-observability` branch since I had made some changes which I needed to keep.
> 
> Not too sure that was really required here, the changes to `stream-to-file` should have had minimal conflicts with the metrics work.

I think it was because I had made a lot of changes to `stream-to-file` which wouldn't have been kept if I had created the branch off of `main`.

**Comment by DanNixon** [comment]
> > > > There is some issue with the Git history of this PR. Did you create the branch fresh from `main` before starting work?
> > > 
> > > 
> > > I deliberately created the branch off of the `metrics-for-observability` branch since I had made some changes which I needed to keep.
> > 
> > 
> > Not too sure that was really required here, the changes to `stream-to-file` should have had minimal conflicts with the metrics work.
> 
> I think it was because I had made a lot of changes to `stream-to-file` which wouldn't have been kept if I had created the branch off of `main`.

Well, sort of, but Git allows multiple pieces of work to happen at once. There is no reason why this work could not have been started from `main`.

**Comment by Henry-Denny** [comment]
> > > > > There is some issue with the Git history of this PR. Did you create the branch fresh from `main` before starting work?
> > > > 
> > > > 
> > > > I deliberately created the branch off of the `metrics-for-observability` branch since I had made some changes which I needed to keep.
> > > 
> > > 
> > > Not too sure that was really required here, the changes to `stream-to-file` should have had minimal conflicts with the metrics work.
> > 
> > 
> > I think it was because I had made a lot of changes to `stream-to-file` which wouldn't have been kept if I had created the branch off of `main`.
> 
> Well, sort of, but Git allows multiple pieces of work to happen at once. There is no reason why this work could not have been started from `main`.

Is it maybe worth deleting this pull request altogether, creating a new branch off of `main` (making the same changes) and then creating another pull request since it seems like I've made a mess of this one?

**Pull request closed without merging**
